# Adding Parameters so that i can change in future from here
AUGMENTATION: True
IMAGE_SIZE: [224,224,3] #as per VGG model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01